---
title: "Reproducible Research: Peer Assessment 1"
author: "Ryan Meyer"
date: "February 14, 2015"
output: html_document
---

## Loading and preprocessing the data
```{r, echo = TRUE}
unzip("activity.zip")
df <- read.csv("activity.csv", header=TRUE, sep=",", quote="\"")
```

## What is mean total number of steps taken per day?
```{r, echo = TRUE}
countStepsPerDay <- aggregate(steps ~ date, df, sum)
hist(countStepsPerDay$steps, main="Total Steps per Day", xlab="Steps")

mean(countStepsPerDay$steps) # mean of total steps per day
median(countStepsPerDay$steps) # median of total steps per day
```

## What is the average daily activity pattern?
```{r, echo = TRUE}
dfDaily <- aggregate(steps ~ interval, df, mean)
plot(dfDaily$interval, dfDaily$steps, 
   type="l", 
   xlab="5 Minute Intervals", 
   ylab="Steps Taken", 
   main="Steps Taken per Interval")
head(dfDaily[order(-dfDaily[,2]), ], 1)$interval # 5 minute interval with maximum steps
```

## Imputing missing values
```{r, echo = TRUE}
nrow(subset(df, is.na(steps) == TRUE)) # count of NA values for steps
meanSteps <- aggregate(steps ~ date, df, mean)
meanStep <- mean(meanSteps$steps) # mean of steps taken across entire data set.
dfNoNa <- df
dfNoNa$steps[is.na(dfNoNa$steps)] <- meanStep

countStepsPerDayNoNa <- aggregate(steps ~ date, dfNoNa, sum)
hist(countStepsPerDayNoNa$steps, main="Total Steps per Day", xlab="Steps")

mean(countStepsPerDayNoNa$steps) # mean of steps per day with imputed values
median(countStepsPerDayNoNa$steps) # median of steps per day with imputed values
```
Missing values made the median match the mean. The imputed histogram also has a higher frequency across all 
bars.

## Are there differences in activity patterns between weekdays and weekends?
```{r, echo = TRUE}
library(lattice)

dfNoNa$dayType <- ifelse (weekdays(as.POSIXct(dfNoNa$date)) == "Sunday" | weekdays(as.POSIXct(dfNoNa$date)) == "Saturday", "Weekend", "Weekday")

weekend <- aggregate(steps ~ interval, subset(dfNoNa, dayType == "Weekend"), mean)
weekend$dayType <- "Weekend"
weekday <- aggregate(steps ~ interval, subset(dfNoNa, dayType == "Weekday"), mean)
weekday$dayType <- "Weekday"

ww <- rbind(weekend, weekday)

xyplot(steps ~ interval | factor(dayType), 
       data=ww, 
       type="l",
       layout=c(1,2),
       xlab="Interval",
       ylab="Number of steps")
```
